import type { CatalogBackend } from './catalogBackend'

/** Exhaustive method inventory shared by unavailable backends. */
export const CATALOG_METHODS = {
  queries: {
    homeLoad: true,
    homeSearch: true,
    listVideos: true,
    getVideo: true,
    listVideoYears: true,
    resolveScrapeFields: true,
    listVideoSources: true,
    getResource: true,
    listTags: true,
    listManualTags: true,
    tagLabels: true,
    tagFilterOptions: true,
    tagManualOptions: true,
    overviewStats: true,
  },
  videos: {
    edit: true,
    clearMeta: true,
    markScrapeSuccess: true,
    markScrapeFailed: true,
    setRating: true,
    setPoster: true,
    importSamples: true,
    deleteSample: true,
    addManualTag: true,
    addExistingManualTag: true,
    removeManualTag: true,
    correctImport: true,
    importResource: true,
    updateResource: true,
    updateLocalResourceLabel: true,
    setPrimaryResource: true,
    removeResource: true,
    previewRemoveFromLibrary: true,
    removeFromLibrary: true,
    previewMoveResource: true,
    moveResource: true,
    previewDeleteGlobal: true,
    deleteGlobal: true,
    merge: true,
    splitResource: true,
    applyScrapeCandidate: true,
  },
  actresses: {
    list: true,
    listPage: true,
    pickerPage: true,
    pickerGet: true,
    get: true,
    profile: true,
    metadata: true,
    videoPage: true,
    galleryPage: true,
    avatarSourceInfo: true,
    mergeCandidates: true,
    edit: true,
    delete: true,
    deleteBatch: true,
    deletePreview: true,
    clearMeta: true,
    importGallery: true,
    deleteGallery: true,
    setPoster: true,
    merge: true,
    markScrapeSuccess: true,
    markScrapeFailed: true,
    applyCrop: true,
    applyScrapeCandidate: true,
    submitConflict: true,
    testTargetPage: true,
    conflictList: true,
    conflictQueuePage: true,
    conflictGet: true,
    conflictCount: true,
    conflictSummary: true,
    inspectName: true,
    discardConflict: true,
    validateIllegal: true,
    resolveConflict: true,
  },
  classifications: {
    listOrganizations: true,
    pageOrganizations: true,
    getOrganization: true,
    createOrganization: true,
    updateOrganization: true,
    mergeOrganizations: true,
    deleteOrganization: true,
    organizationOptions: true,
    organizationMergeOptions: true,
    organizationRoleRemovePreview: true,
    organizationRoleRemove: true,
    organizationDeletePreview: true,
    listDirectors: true,
    pageDirectors: true,
    getDirector: true,
    createDirector: true,
    updateDirector: true,
    mergeDirectors: true,
    deleteDirector: true,
    directorOptions: true,
    directorDeletePreview: true,
    listSeries: true,
    pageSeries: true,
    getSeries: true,
    createSeries: true,
    updateSeries: true,
    mergeSeries: true,
    deleteSeries: true,
    seriesOptions: true,
    seriesDeletePreview: true,
    imagePage: true,
    imageCandidates: true,
    setImage: true,
  },
  playlists: {
    list: true,
    listPage: true,
    get: true,
    getPage: true,
    metadata: true,
    videoPage: true,
    listForVideo: true,
    create: true,
    update: true,
    delete: true,
    addVideo: true,
    removeVideo: true,
    applyImport: true,
  },
  libraries: {
    list: true,
    get: true,
    create: true,
    update: true,
    updateConfig: true,
    addRoot: true,
    updateRoot: true,
    removeRoot: true,
    cancelRootRemoval: true,
    archive: true,
    restore: true,
    deletePreview: true,
    delete: true,
    runScan: true,
    cancelScan: true,
    latestScan: true,
    auditGet: true,
    auditHeader: true,
    auditPage: true,
    auditViewPage: true,
    getPendingScan: true,
    listPendingScans: true,
    pagePendingScanQueue: true,
    countPendingScanQueue: true,
    getPendingResourceIdentity: true,
    listPendingResourceIdentities: true,
    pendingAuditPresence: true,
    previewRenameFile: true,
    renameFile: true,
    importManual: true,
    resolvePendingScan: true,
    resolveResourceIdentity: true,
  },
  nfo: {
    getOptions: true,
    updatePreferences: true,
    plan: true,
    discardPlan: true,
    start: true,
    terminate: true,
    state: true,
  },
  browser: {
    status: true,
    setEnabled: true,
    pairOpen: true,
    pairInspect: true,
    pairDecide: true,
    deviceRemove: true,
    deviceRename: true,
    deviceReset: true,
    revokeSessions: true,
  },
  tasks: {
    get: true,
    list: true,
    cancel: true,
    getOperation: true,
    createTargetList: true,
    countTargets: true,
    pageTargetList: true,
  },
  pendingVideoScrapes: {
    count: true,
    existingIds: true,
    page: true,
    get: true,
    list: true,
    replace: true,
    confirm: true,
    discard: true,
  },
  agentMetadata: {
    preview: true,
    findReady: true,
    apply: true,
    discard: true,
  },
  assets: {
    createUpload: true,
    inspectUpload: true,
    putUpload: true,
    grantPlayback: true,
    readImage: true,
  },
  migration: {
    preview: true,
    start: true,
    status: true,
    enable: true,
    abandon: true,
    putPackage: true,
  },
} as const satisfies {
  [S in CatalogMethodSlice]: {
    [M in keyof CatalogBackend[S]]: true
  }
}

export type CatalogMethodSlice = Exclude<keyof CatalogBackend,
  'mode' | 'identity' | 'generation' | 'capabilities' | 'session' | 'reconnect' | 'claimWriter' | 'dispose'>

export function rejectingCatalogSlice<S extends CatalogMethodSlice>(
  slice: S,
  reject: () => Promise<never>
): CatalogBackend[S] {
  // Every inventory entry receives the same always-rejecting implementation.
  return Object.fromEntries(
    Object.keys(CATALOG_METHODS[slice]).map(key => [key, reject])
  ) as unknown as CatalogBackend[S]
}
