import type { VersionScope } from '../protocol/versions'

export type ManageAuthClass =
  | 'publicHandshake'
  | 'manageRead'
  | 'manageWrite'
  | 'claim'
  | 'migration'

export type ManageCompletion = 'sync' | 'preview' | 'task'

export interface ManageOperationMeta {
  auth: ManageAuthClass
  versions: VersionScope[]
  completion: ManageCompletion
  summary: string
}

export const MANAGE_OPERATIONS = {
  'handshake.get': { auth: 'publicHandshake', versions: [], completion: 'sync', summary: 'Protocol, app, schema, identity, readiness' },
  'writer.status': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Current writer epoch and claim state' },
  'writer.claim': { auth: 'claim', versions: [], completion: 'sync', summary: 'Redeem one-time token with pre-saved candidate secret' },
  'writer.claimStatus': { auth: 'claim', versions: [], completion: 'sync', summary: 'Idempotent claim result by claimId' },
  'writer.handoffBegin': { auth: 'manageWrite', versions: [], completion: 'sync', summary: 'Issue a one-time handoff token without revoking the current writer yet' },
  'writer.recoverIssue': { auth: 'publicHandshake', versions: [], completion: 'sync', summary: 'Issue a deploy-side recovery one-time token' },
  'uploads.create': { auth: 'manageWrite', versions: [], completion: 'sync', summary: 'Create a purpose-scoped image upload slot' },
  'uploads.inspect': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Inspect a completed unconsumed upload' },
  'play.grant': { auth: 'manageRead', versions: ['R', 'G'], completion: 'sync', summary: 'Issue a 12-hour resource-scoped playback grant' },
  'tasks.get': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Task snapshot by id' },
  'tasks.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Active and recent catalog tasks' },
  'tasks.cancel': { auth: 'manageWrite', versions: [], completion: 'task', summary: 'Request cancel; waits for a safe boundary' },
  'operations.get': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Persistent operation receipt' },
  'targetLists.create': { auth: 'manageWrite', versions: [], completion: 'sync', summary: 'Freeze a bounded target id list for batch work' },
  'targetLists.page': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Page a frozen target list' },
  'migration.preview': { auth: 'migration', versions: [], completion: 'preview', summary: 'Compute freeze-ready migration impact' },
  'migration.start': { auth: 'migration', versions: [], completion: 'task', summary: 'Freeze source and transfer into an empty target' },
  'migration.status': { auth: 'migration', versions: [], completion: 'sync', summary: 'Persistent migration phase' },
  'migration.allowEnable': { auth: 'migration', versions: [], completion: 'sync', summary: 'Source persists enable permission before sending it' },
  'migration.enable': { auth: 'migration', versions: [], completion: 'sync', summary: 'Target atomically enables or reports already enabled' },
  'migration.abandon': { auth: 'migration', versions: [], completion: 'sync', summary: 'Target permanently abandons; only then may source unfreeze' },
  'home.load': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Home discovery snapshot' },
  'home.search': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Global catalog search' },
  'videos.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Scoped video list' },
  'videos.get': { auth: 'manageRead', versions: ['V', 'R'], completion: 'sync', summary: 'Scoped video detail' },
  'videos.years': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Release years in scope' },
  'videos.edit': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Edit canonical video fields and relations' },
  'videos.clearMeta': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Clear scraped metadata' },
  'videos.markScrapeSuccess': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Mark cumulative scrape success' },
  'videos.setRating': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Set user rating' },
  'videos.correctImport': { auth: 'manageWrite', versions: ['V', 'Q'], completion: 'sync', summary: 'Correct normalized code; pending scrape discard is explicit' },
  'videos.setPoster': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Apply cover/poster from upload or current asset' },
  'videos.importSamples': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Attach sample images from uploads' },
  'videos.deleteSample': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Delete a sample asset' },
  'videos.addManualTag': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Add a manual tag by name' },
  'videos.addExistingManualTag': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Add an existing manual tag by id' },
  'videos.removeManualTag': { auth: 'manageWrite', versions: ['V'], completion: 'sync', summary: 'Remove a manual tag' },
  'videos.importResource': { auth: 'manageWrite', versions: ['V', 'R', 'L'], completion: 'sync', summary: 'Import an external resource into a library member' },
  'videos.getResource': { auth: 'manageRead', versions: ['R'], completion: 'sync', summary: 'Resource detail with display locator' },
  'videos.updateResource': { auth: 'manageWrite', versions: ['R'], completion: 'sync', summary: 'Update an external resource target' },
  'videos.updateLocalResourceLabel': { auth: 'manageWrite', versions: ['R'], completion: 'sync', summary: 'Update local/STRM display name' },
  'videos.setPrimaryResource': { auth: 'manageWrite', versions: ['R'], completion: 'sync', summary: 'Set primary resource in one library' },
  'videos.removeResource': { auth: 'manageWrite', versions: ['V', 'R'], completion: 'sync', summary: 'Remove a resource; last-resource choice is explicit' },
  'videos.previewRemoveFromLibrary': { auth: 'manageRead', versions: ['V', 'R', 'L', 'P'], completion: 'preview', summary: 'Impact preview for removing a member' },
  'videos.removeFromLibrary': { auth: 'manageWrite', versions: ['V', 'R', 'L', 'P'], completion: 'sync', summary: 'Commit member removal from a frozen preview' },
  'videos.previewMoveResource': { auth: 'manageRead', versions: ['V', 'R', 'L'], completion: 'preview', summary: 'Impact preview for moving a resource' },
  'videos.moveResource': { auth: 'manageWrite', versions: ['V', 'R', 'L'], completion: 'sync', summary: 'Commit resource move from a frozen preview' },
  'videos.previewDeleteGlobal': { auth: 'manageRead', versions: ['V', 'R', 'L', 'P'], completion: 'preview', summary: 'Impact preview for deleting a canonical video' },
  'videos.deleteGlobal': { auth: 'manageWrite', versions: ['V', 'R', 'L', 'P'], completion: 'task', summary: 'Delete canonical video and authorized local/STRM files' },
  'videos.merge': { auth: 'manageWrite', versions: ['V', 'R', 'P', 'Q'], completion: 'sync', summary: 'Merge two same-code videos' },
  'videos.splitResource': { auth: 'manageWrite', versions: ['V', 'R'], completion: 'sync', summary: 'Split a non-primary resource into a new identity-pending video' },
  'videos.applyScrapeCandidate': { auth: 'manageWrite', versions: ['V', 'Q'], completion: 'sync', summary: 'Apply a desktop-collected scrape candidate' },
  'pendingVideoScrapes.count': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Pending video scrape count' },
  'pendingVideoScrapes.existingIds': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Video ids that already have pending scrape results' },
  'pendingVideoScrapes.page': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Pending video scrape page' },
  'pendingVideoScrapes.get': { auth: 'manageRead', versions: ['Q'], completion: 'sync', summary: 'Pending video scrape detail' },
  'pendingVideoScrapes.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Pending video scrape list' },
  'pendingVideoScrapes.confirm': { auth: 'manageWrite', versions: ['V', 'Q'], completion: 'sync', summary: 'Confirm a pending scrape candidate' },
  'pendingVideoScrapes.discard': { auth: 'manageWrite', versions: ['V', 'Q'], completion: 'sync', summary: 'Discard a pending scrape result' },
  'tags.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'All tags' },
  'tags.listManual': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Manual tags' },
  'tags.labels': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Tag labels by ids' },
  'tags.filterOptions': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Tag filter options page' },
  'tags.manualOptions': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Manual tag options page' },
  'actresses.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Actress list' },
  'actresses.listPage': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Actress list page' },
  'actresses.pickerPage': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Actress picker page' },
  'actresses.pickerGet': { auth: 'manageRead', versions: ['A'], completion: 'sync', summary: 'Actress picker identity' },
  'actresses.testTargetPage': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Actress test-target page' },
  'actresses.mergeCandidates': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Actress merge candidates' },
  'actresses.galleryPage': { auth: 'manageRead', versions: ['A'], completion: 'sync', summary: 'Actress gallery page' },
  'actresses.profile': { auth: 'manageRead', versions: ['A'], completion: 'sync', summary: 'Actress profile' },
  'actresses.metadata': { auth: 'manageRead', versions: ['A'], completion: 'sync', summary: 'Actress metadata without videos' },
  'actresses.videoPage': { auth: 'manageRead', versions: ['A'], completion: 'sync', summary: 'Actress associated videos page' },
  'actresses.get': { auth: 'manageRead', versions: ['A'], completion: 'sync', summary: 'Actress detail' },
  'actresses.avatarSourceInfo': { auth: 'manageRead', versions: ['A'], completion: 'sync', summary: 'Actress avatar source info' },
  'actresses.edit': { auth: 'manageWrite', versions: ['A'], completion: 'sync', summary: 'Edit actress profile; images via upload refs' },
  'actresses.delete': { auth: 'manageWrite', versions: ['A', 'V'], completion: 'sync', summary: 'Delete one actress' },
  'actresses.deleteBatch': { auth: 'manageWrite', versions: ['A', 'V'], completion: 'sync', summary: 'Batch delete actresses using per-item receipts' },
  'actresses.deletePreview': { auth: 'manageRead', versions: ['A', 'V'], completion: 'preview', summary: 'Actress delete impact' },
  'actresses.clearMeta': { auth: 'manageWrite', versions: ['A'], completion: 'sync', summary: 'Clear actress scraped metadata' },
  'actresses.importGallery': { auth: 'manageWrite', versions: ['A'], completion: 'sync', summary: 'Import gallery images from uploads' },
  'actresses.deleteGallery': { auth: 'manageWrite', versions: ['A'], completion: 'sync', summary: 'Delete a gallery asset' },
  'actresses.setPoster': { auth: 'manageWrite', versions: ['A'], completion: 'sync', summary: 'Set actress avatar from upload or asset' },
  'actresses.merge': { auth: 'manageWrite', versions: ['A', 'V', 'Q'], completion: 'sync', summary: 'Merge two actress records' },
  'actresses.markScrapeSuccess': { auth: 'manageWrite', versions: ['A'], completion: 'sync', summary: 'Mark actress scrape success' },
  'actresses.applyCrop': { auth: 'manageWrite', versions: ['A'], completion: 'sync', summary: 'Apply desktop crop using source image version/digest' },
  'actresses.applyScrapeCandidate': { auth: 'manageWrite', versions: ['A', 'Q'], completion: 'sync', summary: 'Apply a desktop-collected actress scrape candidate' },
  'actressConflicts.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Name conflict groups' },
  'actressConflicts.queuePage': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Conflict queue page' },
  'actressConflicts.get': { auth: 'manageRead', versions: ['Q'], completion: 'sync', summary: 'One pending actress scrape conflict' },
  'actressConflicts.count': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Conflict count' },
  'actressConflicts.summary': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Conflict review summary' },
  'actressConflicts.inspectName': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Inspect a conflicting name' },
  'actressConflicts.discard': { auth: 'manageWrite', versions: ['Q', 'A'], completion: 'sync', summary: 'Discard a pending actress scrape' },
  'actressConflicts.validateIllegal': { auth: 'manageWrite', versions: ['Q', 'A'], completion: 'sync', summary: 'Validate illegal-name replacements' },
  'actressConflicts.resolve': { auth: 'manageWrite', versions: ['Q', 'A', 'V'], completion: 'sync', summary: 'Resolve a pending actress scrape atomically' },
  'organizations.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Organization list' },
  'organizations.page': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Organization page' },
  'organizations.get': { auth: 'manageRead', versions: ['F'], completion: 'sync', summary: 'Organization detail' },
  'organizations.options': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Organization options' },
  'organizations.mergeOptions': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Organization merge options' },
  'organizations.create': { auth: 'manageWrite', versions: ['F'], completion: 'sync', summary: 'Create organization' },
  'organizations.update': { auth: 'manageWrite', versions: ['F'], completion: 'sync', summary: 'Update organization' },
  'organizations.merge': { auth: 'manageWrite', versions: ['F', 'V'], completion: 'sync', summary: 'Merge organizations' },
  'organizations.roleRemovePreview': { auth: 'manageRead', versions: ['F', 'V'], completion: 'preview', summary: 'Role-remove impact' },
  'organizations.roleRemove': { auth: 'manageWrite', versions: ['F', 'V'], completion: 'sync', summary: 'Remove an organization role' },
  'organizations.deletePreview': { auth: 'manageRead', versions: ['F', 'V'], completion: 'preview', summary: 'Organization delete impact' },
  'organizations.delete': { auth: 'manageWrite', versions: ['F', 'V'], completion: 'sync', summary: 'Delete organization' },
  'directors.page': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Director page' },
  'directors.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Director list' },
  'directors.get': { auth: 'manageRead', versions: ['F'], completion: 'sync', summary: 'Director detail' },
  'directors.options': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Director options' },
  'directors.create': { auth: 'manageWrite', versions: ['F'], completion: 'sync', summary: 'Create director' },
  'directors.update': { auth: 'manageWrite', versions: ['F'], completion: 'sync', summary: 'Update director' },
  'directors.merge': { auth: 'manageWrite', versions: ['F', 'V'], completion: 'sync', summary: 'Merge directors' },
  'directors.deletePreview': { auth: 'manageRead', versions: ['F', 'V'], completion: 'preview', summary: 'Director delete impact' },
  'directors.delete': { auth: 'manageWrite', versions: ['F', 'V'], completion: 'sync', summary: 'Delete director' },
  'series.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Series list' },
  'series.page': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Series page' },
  'series.get': { auth: 'manageRead', versions: ['F'], completion: 'sync', summary: 'Series detail' },
  'series.options': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Series options' },
  'series.create': { auth: 'manageWrite', versions: ['F'], completion: 'sync', summary: 'Create series' },
  'series.update': { auth: 'manageWrite', versions: ['F'], completion: 'sync', summary: 'Update series' },
  'series.merge': { auth: 'manageWrite', versions: ['F', 'V'], completion: 'sync', summary: 'Merge series' },
  'series.deletePreview': { auth: 'manageRead', versions: ['F', 'V'], completion: 'preview', summary: 'Series delete impact' },
  'series.delete': { auth: 'manageWrite', versions: ['F', 'V'], completion: 'sync', summary: 'Delete series' },
  'classificationImages.page': { auth: 'manageRead', versions: ['F'], completion: 'sync', summary: 'Classification image page' },
  'classificationImages.candidates': { auth: 'manageRead', versions: ['F'], completion: 'sync', summary: 'Classification image candidates' },
  'classificationImages.set': { auth: 'manageWrite', versions: ['F'], completion: 'sync', summary: 'Set classification image from upload, asset, or video cover' },
  'playlists.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Playlist list' },
  'playlists.listPage': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Playlist list page' },
  'playlists.get': { auth: 'manageRead', versions: ['P'], completion: 'sync', summary: 'Playlist detail' },
  'playlists.getPage': { auth: 'manageRead', versions: ['P'], completion: 'sync', summary: 'Playlist page' },
  'playlists.metadata': { auth: 'manageRead', versions: ['P'], completion: 'sync', summary: 'Playlist metadata' },
  'playlists.videoPage': { auth: 'manageRead', versions: ['P'], completion: 'sync', summary: 'Playlist videos page' },
  'playlists.create': { auth: 'manageWrite', versions: ['P'], completion: 'sync', summary: 'Create playlist' },
  'playlists.update': { auth: 'manageWrite', versions: ['P'], completion: 'sync', summary: 'Update playlist metadata/cover/links' },
  'playlists.delete': { auth: 'manageWrite', versions: ['P'], completion: 'sync', summary: 'Delete playlist' },
  'playlists.listForVideo': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Playlists containing a video' },
  'playlists.addVideo': { auth: 'manageWrite', versions: ['P'], completion: 'sync', summary: 'Add an existing video to a playlist' },
  'playlists.removeVideo': { auth: 'manageWrite', versions: ['P'], completion: 'sync', summary: 'Remove a video from a playlist' },
  'playlists.applyImport': { auth: 'manageWrite', versions: ['P', 'L', 'V'], completion: 'sync', summary: 'Atomically apply a desktop-collected playlist import plan' },
  'libraries.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Media library list' },
  'libraries.get': { auth: 'manageRead', versions: ['L', 'C', 'G'], completion: 'sync', summary: 'Media library detail' },
  'libraries.create': { auth: 'manageWrite', versions: ['L'], completion: 'sync', summary: 'Create media library' },
  'libraries.update': { auth: 'manageWrite', versions: ['L'], completion: 'sync', summary: 'Update media library row' },
  'libraries.updateConfig': { auth: 'manageWrite', versions: ['C'], completion: 'sync', summary: 'Update library config' },
  'libraries.addRoot': { auth: 'manageWrite', versions: ['L', 'G'], completion: 'sync', summary: 'Add a deployment-allowed mount selection as a root' },
  'libraries.updateRoot': { auth: 'manageWrite', versions: ['G'], completion: 'sync', summary: 'Update root state/position; rebind is remote-unavailable' },
  'libraries.removeRoot': { auth: 'manageWrite', versions: ['L', 'G', 'R'], completion: 'task', summary: 'Remove a root after preview' },
  'libraries.cancelRootRemoval': { auth: 'manageWrite', versions: ['G'], completion: 'sync', summary: 'Cancel an unfinished root removal' },
  'libraries.archive': { auth: 'manageWrite', versions: ['L'], completion: 'sync', summary: 'Archive a library' },
  'libraries.restore': { auth: 'manageWrite', versions: ['L'], completion: 'sync', summary: 'Restore an archived library' },
  'libraries.deletePreview': { auth: 'manageRead', versions: ['L', 'R', 'G'], completion: 'preview', summary: 'Library delete impact' },
  'libraries.delete': { auth: 'manageWrite', versions: ['L', 'R', 'G'], completion: 'task', summary: 'Delete a library after preview' },
  'scans.run': { auth: 'manageWrite', versions: ['L', 'C', 'G'], completion: 'task', summary: 'Start a library scan' },
  'scans.cancel': { auth: 'manageWrite', versions: [], completion: 'task', summary: 'Request scan cancel at a safe boundary' },
  'scans.getLatest': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Latest scan summary' },
  'scans.auditGet': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Legacy audit blob' },
  'scans.auditHeader': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Audit header' },
  'scans.auditPage': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Audit page' },
  'scans.auditViewPage': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Audit view page' },
  'files.rename': { auth: 'manageWrite', versions: ['G', 'R'], completion: 'preview', summary: 'Rename a local source file after preview' },
  'files.importManual': { auth: 'manageWrite', versions: ['V', 'R', 'G'], completion: 'sync', summary: 'Manually import a file inside an authorized root' },
  'pendingAudit.presence': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Whether pending audit items exist' },
  'pendingScan.queuePage': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Pending scan queue page' },
  'pendingScan.queueCount': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Pending scan queue count' },
  'pendingScan.get': { auth: 'manageRead', versions: ['Q'], completion: 'sync', summary: 'Pending scan group' },
  'pendingScan.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Pending scan groups' },
  'pendingScan.resolve': { auth: 'manageWrite', versions: ['Q', 'V', 'R', 'G'], completion: 'sync', summary: 'Atomically assign a pending scan group' },
  'pendingResourceIdentity.get': { auth: 'manageRead', versions: ['Q'], completion: 'sync', summary: 'Pending resource identity' },
  'pendingResourceIdentity.list': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Pending resource identities' },
  'pendingResourceIdentity.resolve': { auth: 'manageWrite', versions: ['Q', 'V', 'R', 'G'], completion: 'sync', summary: 'Resolve filename vs NFO identity' },
  'nfo.getOptions': { auth: 'manageRead', versions: ['C'], completion: 'sync', summary: 'NFO export options' },
  'nfo.updatePreferences': { auth: 'manageWrite', versions: ['C'], completion: 'sync', summary: 'NFO export preferences' },
  'nfo.plan': { auth: 'manageWrite', versions: ['C', 'V', 'R', 'G'], completion: 'preview', summary: 'Create a 10-minute NFO plan' },
  'nfo.discardPlan': { auth: 'manageWrite', versions: [], completion: 'sync', summary: 'Discard an NFO plan' },
  'nfo.start': { auth: 'manageWrite', versions: ['C', 'V', 'R', 'G'], completion: 'task', summary: 'Start NFO export from a live plan' },
  'nfo.terminate': { auth: 'manageWrite', versions: [], completion: 'task', summary: 'Terminate an NFO export task' },
  'nfo.state': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'NFO export state' },
  'browser.status': { auth: 'manageRead', versions: ['C'], completion: 'sync', summary: 'Browser pairing status without secrets' },
  'browser.setEnabled': { auth: 'manageWrite', versions: ['C'], completion: 'sync', summary: 'Enable or disable the browser surface; management stays up' },
  'browser.pairOpen': { auth: 'manageWrite', versions: ['C'], completion: 'sync', summary: 'Open a pairing window' },
  'browser.pairInspect': { auth: 'manageRead', versions: ['C'], completion: 'sync', summary: 'Inspect a pairing request' },
  'browser.pairDecide': { auth: 'manageWrite', versions: ['C'], completion: 'sync', summary: 'Approve or deny pairing' },
  'browser.deviceRemove': { auth: 'manageWrite', versions: ['C'], completion: 'sync', summary: 'Remove a paired device' },
  'browser.deviceRename': { auth: 'manageWrite', versions: ['C'], completion: 'sync', summary: 'Rename a paired device' },
  'browser.deviceReset': { auth: 'manageWrite', versions: ['C'], completion: 'sync', summary: 'Reset a paired device' },
  'browser.revokeSessions': { auth: 'manageWrite', versions: ['C'], completion: 'sync', summary: 'Revoke browser sessions without stopping management HTTP' },
  'catalog.overviewStats': { auth: 'manageRead', versions: [], completion: 'sync', summary: 'Catalog overview statistics' },
  'agentMetadata.findReady': { auth: 'manageRead', versions: ['V', 'A', 'F'], completion: 'sync', summary: 'Read-only lookup for desktop metadata collection' },
  'agentMetadata.apply': { auth: 'manageWrite', versions: ['V', 'A', 'F', 'Q'], completion: 'sync', summary: 'Apply structured metadata collection candidates' },
  'agentMetadata.discard': { auth: 'manageWrite', versions: ['Q'], completion: 'sync', summary: 'Discard a metadata collection draft on the catalog' }
} as const satisfies Record<string, ManageOperationMeta>

export type ManageOperationId = keyof typeof MANAGE_OPERATIONS
