import assert from 'node:assert/strict'
import os from 'node:os'
import path from 'node:path'
import fs from 'node:fs'
import { createServer } from 'vite'
import react from '@vitejs/plugin-react'
import { chromium } from 'playwright-core'

// Small PR suite: production Modules, synthetic data, actual browser input. No personal catalog.
const repo = process.cwd()
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'javdex-ui-regression-'))
let server, browser
try {
  server = await createServer({ configFile: false, root: path.join(repo, 'scripts/ui-regression'),
    cacheDir: path.join(temporary, '.vite'), plugins: [react()],
    resolve: { alias: { '@shared': path.join(repo, 'packages/contracts/src'), react: path.join(repo, 'node_modules/react'), 'react-dom': path.join(repo, 'node_modules/react-dom') } },
    server: { host: '127.0.0.1', port: 0, watch: null, fs: { allow: [repo] } } })
  await server.listen()
  browser = await chromium.launch({ ...(process.env.JAVDEX_BROWSER_EXECUTABLE
    ? { executablePath: process.env.JAVDEX_BROWSER_EXECUTABLE } : { channel: process.env.JAVDEX_BROWSER_CHANNEL || 'chrome' }), headless: true })
  const page = await browser.newPage({ viewport: { width: 1000, height: 700 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}`)
  await page.waitForFunction(() => typeof window.finishOldRead === 'function')
  await page.getByRole('button', { name: '切换浏览会话' }).click()
  await page.waitForFunction(() => document.querySelector('[data-session]').textContent === 'second')
  await page.evaluate(() => window.finishOldRead())
  await page.waitForTimeout(50)
  assert.equal(await page.locator('[data-session]').innerText(), 'second', 'old request cannot roll the new session back')
  const opener = page.getByRole('button', { name: '打开弹窗', exact: true })
  await page.evaluate(() => {
    const existing = document.createElement('aside')
    existing.id = 'previously-inert'
    existing.inert = true
    document.body.append(existing)
  })
  await opener.click()
  const outer = page.getByRole('dialog', { name: '外层弹窗', exact: true })
  await outer.waitFor()
  assert.equal(await page.evaluate(() => document.body.style.overflow), 'hidden')
  assert.equal(await opener.evaluate(element => element.closest('[inert]') != null), true, 'background controls are inert')
  await page.evaluate(() => {
    const late = document.createElement('button')
    late.id = 'late-background'
    late.textContent = '晚加入背景按钮'
    document.body.append(late)
  })
  await page.waitForFunction(() => document.getElementById('late-background').inert)
  await page.getByRole('combobox', { name: '所属机构' }).focus()
  await page.getByRole('listbox', { name: '机构候选' }).waitFor()
  await page.keyboard.press('Tab')
  await page.getByRole('listbox', { name: '机构候选' }).waitFor({ state: 'detached' })
  assert.equal(await page.getByRole('textbox', { name: '后续字段' }).evaluate(element => document.activeElement === element), true,
    'Tab skips aria-activedescendant candidates and does not restore the blurred combobox')
  const select = page.getByRole('button', { name: '选项', exact: true })
  await select.click()
  await page.keyboard.press('Tab')
  assert.equal(await page.getByRole('option').first().evaluate(element => document.activeElement === element), true, 'Tab includes the portaled listbox')
  await page.keyboard.press('Escape')
  assert.equal(await page.getByRole('listbox').count(), 0)
  assert.equal(await outer.count(), 1, 'Escape closes only the select')
  assert.equal(await select.evaluate(element => document.activeElement === element), true)
  await page.getByRole('button', { name: '打开浮层', exact: true }).click()
  await page.getByRole('button', { name: '浮层选项' }).click()
  await page.getByRole('option', { name: '第二项' }).click()
  assert.equal(await page.getByRole('dialog', { name: '嵌套浮层' }).count(), 1, 'portaled child selection keeps parent open')
  await page.keyboard.press('Escape')
  assert.equal(await page.getByRole('dialog', { name: '嵌套浮层' }).count(), 0)
  await page.getByRole('button', { name: '打开子弹窗' }).click()
  const child = page.getByRole('dialog', { name: '子弹窗', exact: true })
  for (let i = 0; i < 6; i++) {
    await page.keyboard.press(i % 2 ? 'Shift+Tab' : 'Tab')
    assert.equal(await child.evaluate(element => element.contains(document.activeElement)), true)
  }
  await page.keyboard.press('Escape')
  assert.equal(await child.count(), 0)
  assert.equal(await outer.count(), 1)
  const input = page.getByRole('textbox', { name: '草稿', exact: true })
  const pluginMenu = outer.getByRole('button', { name: '更多操作', exact: true })
  await pluginMenu.click()
  await page.getByRole('menu').waitFor()
  await input.click()
  await page.getByRole('menu').waitFor({ state: 'detached' })
  assert.equal(await input.evaluate(element => document.activeElement === element), true, 'outside-click dismissal keeps the clicked input focused')
  await pluginMenu.click()
  await page.keyboard.press('Escape')
  assert.equal(await page.getByRole('menu').count(), 0)
  assert.equal(await pluginMenu.evaluate(element => document.activeElement === element), true, 'non-focusable positioning wrapper restores the real trigger on Escape')
  assert.equal(await outer.count(), 1)
  await input.focus()
  await input.dispatchEvent('keydown', { key: 'Escape', isComposing: true })
  assert.equal(await outer.count(), 1, 'composition Escape is ignored')
  await page.getByRole('button', { name: '打开图片预览' }).click()
  const preview = page.getByRole('dialog', { name: '合成图片预览' })
  await preview.waitFor()
  await page.keyboard.press('Tab')
  assert.equal(await preview.evaluate(element => element.contains(document.activeElement)), true)
  await page.keyboard.press('Escape')
  await preview.waitFor({ state: 'detached' })
  assert.equal(await page.evaluate(() => document.body.style.overflow), 'hidden', 'closing preview retains parent scroll lock')
  assert.equal(await outer.count(), 1)
  await page.getByRole('button', { name: '打开图片预览' }).click()
  await preview.waitFor()
  await page.evaluate(() => window.history.back())
  await preview.waitFor({ state: 'detached' })
  assert.equal(await outer.count(), 1, 'browser Back closes the history-owned preview, not its parent')
  await page.getByRole('button', { name: '确认', exact: true }).click()
  await page.keyboard.press('Escape')
  assert.equal(await outer.count(), 1, 'saving dialog consumes Escape without dismissal')
  assert.equal(await input.inputValue(), '保留内容')
  await page.evaluate(() => window.finishSave())
  await page.getByRole('button', { name: '确认', exact: true }).waitFor({ state: 'visible' })
  await page.waitForFunction(() => !document.querySelector('[role="dialog"]').hasAttribute('aria-busy'))
  await page.keyboard.press('Escape')
  assert.equal(await outer.count(), 0)
  assert.equal(await page.evaluate(() => document.body.style.overflow), 'auto')
  assert.equal(await opener.evaluate(element => document.activeElement === element), true)
  assert.equal(await opener.evaluate(element => element.closest('[inert]') == null), true)
  assert.equal(await page.evaluate(() => document.getElementById('previously-inert').inert), true, 'pre-existing inert state is preserved')
  assert.equal(await page.evaluate(() => document.getElementById('late-background').inert), false)
  const taskOpener = page.getByRole('button', { name: '打开前台任务' })
  await taskOpener.click()
  const task = page.getByRole('dialog', { name: '正在导出影片资料' })
  await task.waitFor()
  await page.keyboard.press('Control+k')
  await page.keyboard.press('Escape')
  assert.equal(await task.count(), 1, 'foreground task consumes dismissal')
  assert.equal(await page.evaluate(() => window.globalShortcutCalls), 0, 'capture policy blocks an earlier global shortcut listener')
  await page.keyboard.press('Tab')
  assert.equal(await task.evaluate(element => element.contains(document.activeElement)), true)
  await task.getByRole('button', { name: '停止导出', exact: true }).click()
  assert.equal(await page.evaluate(() => window.terminationRequests), 1)
  await task.getByRole('button', { name: '查看详情', exact: true }).click()
  const taskDetail = page.getByRole('dialog', { name: '操作详情', exact: true })
  await taskDetail.waitFor()
  assert.equal(await page.evaluate(() => {
    const refresh = new KeyboardEvent('keydown', { key: 'r', ctrlKey: true, bubbles: true, cancelable: true })
    document.activeElement.dispatchEvent(refresh)
    return refresh.defaultPrevented
  }), true, 'foreground refresh policy remains active while error details are open')
  await page.keyboard.press('Control+k')
  assert.equal(await page.evaluate(() => window.globalShortcutCalls), 0, 'owned details inherit foreground shortcut blocking')
  await page.keyboard.press('Escape')
  await taskDetail.waitFor({ state: 'detached' })
  assert.equal(await task.count(), 1, 'Escape closes only error details')
  assert.equal(await page.evaluate(() => document.body.style.overflow), 'hidden')
  await page.evaluate(() => window.finishForegroundTask())
  await task.waitFor({ state: 'detached' })
  assert.equal(await taskOpener.count(), 0)
  assert.equal(await page.getByRole('button', { name: '生成预览', exact: true }).evaluate(element => document.activeElement === element), true, 'task has a stable return-focus target after its original trigger is removed')
  assert.equal(await page.evaluate(() => document.body.style.overflow), 'auto')
  await page.keyboard.press('Control+k')
  assert.equal(await page.evaluate(() => window.globalShortcutCalls), 1, 'global shortcut resumes after task cleanup')
  assert.deepEqual(errors, [])
  console.log('UI regression passed: stale session, portal ownership, combobox Tab/focus, composition, nested Escape, preview Back/history/scroll lock, inert restoration, async confirmation, foreground task/detail shortcuts.')
} finally {
  await browser?.close()
  await server?.close()
  fs.rmSync(temporary, { recursive: true, force: true })
}
