import { IPC } from '../ipc-channels'
import type { ManageOperationId } from '../manage/operations'
import type { VersionScope } from '../protocol/versions'

export type IpcDispositionKind =
  | 'desktopRetain'
  | 'desktopWorkflow'
  | 'manageQuery'
  | 'manageMutation'
  | 'catalogTask'
  | 'desktopEvent'
  | 'remoteUnavailable'
  | 'compatMerged'

export interface IpcDisposition {
  kind: IpcDispositionKind
  manageUseCase?: ManageOperationId
  desktopUseCase?: string
  versions: readonly VersionScope[]
  completion: 'sync' | 'preview' | 'task' | 'event' | 'none'
  compatTarget?: keyof typeof IPC
  notes: string
}

const desktop = (notes: string, desktopUseCase?: string): IpcDisposition => ({
  kind: 'desktopRetain',
  desktopUseCase,
  versions: [],
  completion: 'none',
  notes
})

const unavailable = (notes: string): IpcDisposition => ({
  kind: 'remoteUnavailable',
  versions: [],
  completion: 'none',
  notes
})

const event = (notes: string, manageUseCase?: ManageOperationId): IpcDisposition => ({
  kind: 'desktopEvent',
  manageUseCase,
  versions: [],
  completion: 'event',
  notes
})

const query = (manageUseCase: ManageOperationId, versions: VersionScope[] = [], notes = ''): IpcDisposition => ({
  kind: 'manageQuery',
  manageUseCase,
  versions,
  completion: 'sync',
  notes
})

const mutate = (
  manageUseCase: ManageOperationId,
  versions: VersionScope[],
  completion: 'sync' | 'preview' | 'task' = 'sync',
  notes = ''
): IpcDisposition => ({
  kind: 'manageMutation',
  manageUseCase,
  versions,
  completion,
  notes
})

const task = (manageUseCase: ManageOperationId, versions: VersionScope[], notes = ''): IpcDisposition => ({
  kind: 'catalogTask',
  manageUseCase,
  versions,
  completion: 'task',
  notes
})

const workflow = (
  desktopUseCase: string,
  manageUseCase: ManageOperationId | undefined,
  versions: VersionScope[],
  notes = ''
): IpcDisposition => ({
  kind: 'desktopWorkflow',
  desktopUseCase,
  manageUseCase,
  versions,
  completion: manageUseCase ? 'sync' : 'none',
  notes
})

export const IPC_DISPOSITION = {
  MEDIA_LIBRARY_LIST: query('libraries.list'),
  MEDIA_LIBRARY_GET: query('libraries.get', ['L', 'C', 'G']),
  MEDIA_LIBRARY_CREATE: mutate('libraries.create', ['L']),
  MEDIA_LIBRARY_UPDATE: mutate('libraries.update', ['L']),
  MEDIA_LIBRARY_CONFIG_UPDATE: mutate('libraries.updateConfig', ['C']),
  MEDIA_LIBRARY_ROOT_ADD: mutate('libraries.addRoot', ['L', 'G'], 'sync', 'Remote input is mountSelectionId, never a host path'),
  MEDIA_LIBRARY_ROOT_UPDATE: mutate('libraries.updateRoot', ['G'], 'sync', 'State/position only; rebind remains remote-unavailable'),
  MEDIA_LIBRARY_ROOT_REMOVE: task('libraries.removeRoot', ['L', 'G', 'R']),
  MEDIA_LIBRARY_ROOT_REMOVE_CANCEL: mutate('libraries.cancelRootRemoval', ['G']),
  MEDIA_LIBRARY_ROOT_MIGRATE_PREVIEW: unavailable('Local ADR-0024 root rebind only'),
  MEDIA_LIBRARY_ROOT_MIGRATE: unavailable('Local ADR-0024 root rebind only'),
  MEDIA_LIBRARY_ARCHIVE: mutate('libraries.archive', ['L']),
  MEDIA_LIBRARY_RESTORE: mutate('libraries.restore', ['L']),
  MEDIA_LIBRARY_DELETE_PREVIEW: mutate('libraries.deletePreview', ['L', 'R', 'G'], 'preview'),
  MEDIA_LIBRARY_DELETE: task('libraries.delete', ['L', 'R', 'G']),
  HOME_LOAD: query('home.load'),
  HOME_SEARCH: query('home.search'),
  WEB_ACCESS_PAIR_OPEN: mutate('browser.pairOpen', ['C']),
  WEB_ACCESS_PAIR_INSPECT: query('browser.pairInspect', ['C']),
  WEB_ACCESS_PAIR_DECIDE: mutate('browser.pairDecide', ['C']),
  WEB_ACCESS_DEVICE_REMOVE: mutate('browser.deviceRemove', ['C']),
  WEB_ACCESS_DEVICE_RENAME: mutate('browser.deviceRename', ['C']),
  WEB_ACCESS_DEVICE_RESET: mutate('browser.deviceReset', ['C']),
  WEB_ACCESS_STATUS: workflow('webAccess.localStatus', 'browser.status', ['C'], 'Local webAccess stays desktop; remote reads catalog pairing DTO without secrets'),
  WEB_ACCESS_APPLY: workflow('webAccess.localApply', 'browser.setEnabled', ['C'], 'Remote maps enabled only; listen address/port stay deployment config'),
  WEB_ACCESS_REVOKE: mutate('browser.revokeSessions', ['C']),
  SETTINGS_GET: workflow('settings.thisComputer.get', 'catalog.overviewStats', [], 'Splits this-computer vs current-catalog; no writer token in renderer'),
  SETTINGS_UPDATE: workflow('settings.thisComputer.update', undefined, [], 'Catalog-owned settings use dedicated manage ops; this-computer fields stay desktop'),
  SETTINGS_PICK_FOLDER: desktop('Native folder picker'),
  SETTINGS_LIBRARY_PATH_REMOVE_PREVIEW: unavailable('Legacy global libraryPaths; catalog roots use libraries.*'),
  SETTINGS_LIBRARY_PATH_REMOVE_CONFIRM: unavailable('Legacy global libraryPaths; catalog roots use libraries.*'),
  SETTINGS_MODEL_MANAGEMENT_GET: desktop('Model connections stay on this computer'),
  SETTINGS_MODEL_MANAGEMENT_APPLY: desktop('Model connections stay on this computer'),
  SETTINGS_MODEL_MANAGEMENT_DISCOVER_MODELS: desktop('Model discovery stays on this computer'),
  SETTINGS_MODEL_MANAGEMENT_TEST_MODEL: desktop('Model probe stays on this computer'),
  SETTINGS_RECOVERY_REVEAL_BACKUP: desktop('Reveal a local backup file'),
  SETTINGS_PROXY_TEST: desktop('Desktop network probe'),
  SETTINGS_OVERVIEW_STATS: query('catalog.overviewStats'),
  NFO_EXPORT_GET_OPTIONS: query('nfo.getOptions', ['C']),
  NFO_EXPORT_UPDATE_PREFERENCES: mutate('nfo.updatePreferences', ['C']),
  NFO_EXPORT_PLAN: mutate('nfo.plan', ['C', 'V', 'R', 'G'], 'preview'),
  NFO_EXPORT_DISCARD_PLAN: mutate('nfo.discardPlan', []),
  NFO_EXPORT_START: task('nfo.start', ['C', 'V', 'R', 'G']),
  NFO_EXPORT_TERMINATE: task('nfo.terminate', []),
  NFO_EXPORT_PROGRESS: event('Desktop progress from tasks.get', 'tasks.get'),
  NFO_EXPORT_STATE: query('nfo.state'),
  EXTERNAL_LINK_OPEN: desktop('OS handler; no Javdex credentials'),
  APP_UPDATE_GET_STATE: desktop('Desktop release channel'),
  APP_UPDATE_CHECK: desktop('Desktop release channel'),
  APP_UPDATE_OPEN_RELEASE: desktop('Open desktop release URL'),
  APP_UPDATE_OPEN_PROJECT_PAGE: desktop('Open project page'),
  APP_UPDATE_IGNORE_VERSION: desktop('Desktop-only ignore list'),
  APP_UPDATE_STATE_CHANGED: event('Desktop updater event'),
  SCAN_RUN: task('scans.run', ['L', 'C', 'G']),
  SCAN_CANCEL: task('scans.cancel', []),
  SCAN_LATEST_GET: query('scans.getLatest'),
  SCAN_AUDIT_GET: query('scans.auditGet'),
  SCAN_AUDIT_HEADER: query('scans.auditHeader'),
  SCAN_AUDIT_PAGE: query('scans.auditPage'),
  SCAN_AUDIT_VIEW_PAGE: query('scans.auditViewPage'),
  SCAN_AUDIT_REVEAL_FILE: unavailable('Remote reveal is not a file locator; UI uses root name + relative path'),
  SCAN_PROGRESS: event('Desktop task projection', 'tasks.get'),
  SCAN_STATE_CHANGED: event('Desktop task projection', 'tasks.get'),
  FILE_RENAME: mutate('files.rename', ['G', 'R'], 'preview', 'Root-relative location only'),
  FILE_IMPORT_MANUAL: mutate('files.importManual', ['V', 'R', 'G'], 'sync', 'Root-relative location only; desktop absolute paths rejected'),
  PENDING_AUDIT_PRESENCE: query('pendingAudit.presence'),
  PENDING_SCAN_QUEUE_PAGE: query('pendingScan.queuePage'),
  PENDING_SCAN_QUEUE_COUNT: query('pendingScan.queueCount'),
  PENDING_SCAN_GET: query('pendingScan.get', ['Q']),
  PENDING_RESOURCE_IDENTITY_GET: query('pendingResourceIdentity.get', ['Q']),
  PENDING_SCAN_LIST: query('pendingScan.list'),
  PENDING_SCAN_RESOLVE: mutate('pendingScan.resolve', ['Q', 'V', 'R', 'G']),
  PENDING_RESOURCE_IDENTITY_LIST: query('pendingResourceIdentity.list'),
  PENDING_RESOURCE_IDENTITY_RESOLVE: mutate('pendingResourceIdentity.resolve', ['Q', 'V', 'R', 'G']),
  VIDEO_LIST: query('videos.list'),
  VIDEO_GET: query('videos.get', ['V', 'R']),
  VIDEO_UPDATE: {
    kind: 'compatMerged',
    manageUseCase: 'videos.edit',
    compatTarget: 'VIDEO_EDIT',
    versions: ['V'],
    completion: 'sync',
    notes: 'Compatibility alias of videos.edit'
  },
  VIDEO_EDIT: mutate('videos.edit', ['V'], 'sync', 'coverSourcePath becomes catalog image ref'),
  VIDEO_CLEAR_META: mutate('videos.clearMeta', ['V']),
  VIDEO_MARK_SCRAPE_SUCCESS: mutate('videos.markScrapeSuccess', ['V']),
  VIDEO_SET_RATING: mutate('videos.setRating', ['V']),
  VIDEO_CORRECT_IMPORT: mutate('videos.correctImport', ['V', 'Q'], 'sync', 'discardPendingScrape must be explicit'),
  VIDEO_YEARS: query('videos.years'),
  VIDEO_SAMPLE_IMPORT: mutate('videos.importSamples', ['V'], 'sync', 'Uploads or desktop temp handles; no raw host paths on the wire'),
  VIDEO_SAMPLE_DELETE: mutate('videos.deleteSample', ['V']),
  VIDEO_POSTER_SET: mutate('videos.setPoster', ['V'], 'sync', 'Rejects posterPath and unauthorized asset ids'),
  VIDEO_MANUAL_TAG_ADD: mutate('videos.addManualTag', ['V']),
  VIDEO_MANUAL_TAG_ADD_EXISTING: mutate('videos.addExistingManualTag', ['V']),
  VIDEO_MANUAL_TAG_REMOVE: mutate('videos.removeManualTag', ['V']),
  VIDEO_RESOURCE_IMPORT: mutate('videos.importResource', ['V', 'R', 'L']),
  VIDEO_RESOURCE_GET: query('videos.getResource', ['R']),
  VIDEO_RESOURCE_CHECK: desktop('Desktop HEAD probe; not catalog proof'),
  VIDEO_RESOURCE_UPDATE: mutate('videos.updateResource', ['R']),
  VIDEO_RESOURCE_UPDATE_LOCAL_LABEL: mutate('videos.updateLocalResourceLabel', ['R']),
  VIDEO_RESOURCE_SET_PRIMARY: mutate('videos.setPrimaryResource', ['R']),
  VIDEO_RESOURCE_REMOVE: mutate('videos.removeResource', ['V', 'R']),
  VIDEO_REMOVE_FROM_LIBRARY_PREVIEW: mutate('videos.previewRemoveFromLibrary', ['V', 'R', 'L', 'P'], 'preview'),
  VIDEO_REMOVE_FROM_LIBRARY: mutate('videos.removeFromLibrary', ['V', 'R', 'L', 'P']),
  VIDEO_RESOURCE_MOVE_PREVIEW: mutate('videos.previewMoveResource', ['V', 'R', 'L'], 'preview'),
  VIDEO_RESOURCE_MOVE: mutate('videos.moveResource', ['V', 'R', 'L']),
  VIDEO_DELETE_GLOBAL_PREVIEW: mutate('videos.previewDeleteGlobal', ['V', 'R', 'L', 'P'], 'preview'),
  VIDEO_DELETE_GLOBAL: task('videos.deleteGlobal', ['V', 'R', 'L', 'P']),
  VIDEO_MERGE: mutate('videos.merge', ['V', 'R', 'P', 'Q']),
  VIDEO_RESOURCE_SPLIT: mutate('videos.splitResource', ['V', 'R']),
  PLAYLIST_LIST: query('playlists.list'),
  PLAYLIST_LIST_PAGE: query('playlists.listPage'),
  PLAYLIST_GET: query('playlists.get', ['P']),
  PLAYLIST_GET_PAGE: query('playlists.getPage', ['P']),
  PLAYLIST_METADATA: query('playlists.metadata', ['P']),
  PLAYLIST_VIDEO_PAGE: query('playlists.videoPage', ['P']),
  PLAYLIST_CREATE: mutate('playlists.create', ['P']),
  PLAYLIST_UPDATE: mutate('playlists.update', ['P']),
  PLAYLIST_DELETE: mutate('playlists.delete', ['P']),
  PLAYLIST_LIST_FOR_VIDEO: query('playlists.listForVideo'),
  PLAYLIST_ADD_VIDEO: mutate('playlists.addVideo', ['P']),
  PLAYLIST_REMOVE_VIDEO: mutate('playlists.removeVideo', ['P']),
  ACTRESS_LIST: query('actresses.list'),
  ACTRESS_LIST_PAGE: query('actresses.listPage'),
  ACTRESS_PICKER_PAGE: query('actresses.pickerPage'),
  ACTRESS_AVATAR_CROP_TARGETS: workflow('actress.crop.enumerate', undefined, [], 'Face model and target pick stay desktop; images loaded via authorized manage reads'),
  ACTRESS_AVATAR_CROP_COUNT: workflow('actress.crop.count', undefined, [], 'Desktop crop working set'),
  ACTRESS_TEST_TARGET_PAGE: query('actresses.testTargetPage'),
  ACTRESS_TEST_TARGET_GET: query('actresses.pickerGet', ['A']),
  ACTRESS_PICKER_GET: query('actresses.pickerGet', ['A']),
  ACTRESS_MERGE_CANDIDATES: query('actresses.mergeCandidates'),
  ACTRESS_FACE_SCAN_MANIFEST: workflow('actress.faceManifest', 'actresses.listPage', ['A'], 'Desktop face model; catalog supplies authorized image refs not filesystem paths'),
  ACTRESS_GALLERY_PAGE: query('actresses.galleryPage', ['A']),
  ACTRESS_PROFILE: query('actresses.profile', ['A']),
  ACTRESS_METADATA: query('actresses.metadata', ['A']),
  ACTRESS_VIDEO_PAGE: query('actresses.videoPage', ['A']),
  ACTRESS_GET: query('actresses.get', ['A']),
  ACTRESS_AVATAR_SOURCE_INFO: query('actresses.avatarSourceInfo', ['A']),
  ACTRESS_EDIT: mutate('actresses.edit', ['A'], 'sync', 'avatarSourcePath/base64 replaced by image refs'),
  ACTRESS_DELETE: mutate('actresses.delete', ['A', 'V']),
  ACTRESS_DELETE_BATCH: mutate('actresses.deleteBatch', ['A', 'V']),
  ACTRESS_DELETE_PREVIEW: mutate('actresses.deletePreview', ['A', 'V'], 'preview'),
  ACTRESS_CLEAR_META: mutate('actresses.clearMeta', ['A']),
  ACTRESS_GALLERY_IMPORT: mutate('actresses.importGallery', ['A']),
  ACTRESS_GALLERY_DELETE: mutate('actresses.deleteGallery', ['A']),
  ACTRESS_POSTER_SET: mutate('actresses.setPoster', ['A']),
  ACTRESS_MERGE: mutate('actresses.merge', ['A', 'V', 'Q']),
  ACTRESS_MARK_SCRAPE_SUCCESS: mutate('actresses.markScrapeSuccess', ['A']),
  ACTRESS_CONFLICT_LIST: query('actressConflicts.list'),
  ACTRESS_CONFLICT_QUEUE_PAGE: query('actressConflicts.queuePage'),
  ACTRESS_CONFLICT_GET: query('actressConflicts.get', ['Q']),
  ACTRESS_CONFLICT_COUNT: query('actressConflicts.count'),
  ACTRESS_CONFLICT_SUMMARY: query('actressConflicts.summary'),
  ACTRESS_CONFLICT_INSPECT_NAME: query('actressConflicts.inspectName'),
  ACTRESS_CONFLICT_DISCARD: mutate('actressConflicts.discard', ['Q', 'A']),
  ACTRESS_CONFLICT_VALIDATE_ILLEGAL: mutate('actressConflicts.validateIllegal', ['Q', 'A']),
  ACTRESS_CONFLICT_RESOLVE: mutate('actressConflicts.resolve', ['Q', 'A', 'V']),
  TAG_LIST: query('tags.list'),
  TAG_LIST_MANUAL: query('tags.listManual'),
  TAG_LABELS: query('tags.labels'),
  TAG_FILTER_OPTIONS: query('tags.filterOptions'),
  TAG_MANUAL_OPTIONS: query('tags.manualOptions'),
  ORGANIZATION_LIST: query('organizations.list'),
  ORGANIZATION_PAGE: query('organizations.page'),
  ORGANIZATION_GET: query('organizations.get', ['F']),
  ORGANIZATION_OPTIONS: query('organizations.options'),
  ORGANIZATION_MERGE_OPTIONS: query('organizations.mergeOptions'),
  ORGANIZATION_CREATE: mutate('organizations.create', ['F']),
  ORGANIZATION_UPDATE: mutate('organizations.update', ['F']),
  ORGANIZATION_MERGE: mutate('organizations.merge', ['F', 'V']),
  ORGANIZATION_ROLE_REMOVE_PREVIEW: mutate('organizations.roleRemovePreview', ['F', 'V'], 'preview'),
  ORGANIZATION_ROLE_REMOVE: mutate('organizations.roleRemove', ['F', 'V']),
  ORGANIZATION_DELETE_PREVIEW: mutate('organizations.deletePreview', ['F', 'V'], 'preview'),
  ORGANIZATION_DELETE: mutate('organizations.delete', ['F', 'V']),
  DIRECTOR_PAGE: query('directors.page'),
  DIRECTOR_LIST: query('directors.list'),
  DIRECTOR_GET: query('directors.get', ['F']),
  DIRECTOR_OPTIONS: query('directors.options'),
  DIRECTOR_CREATE: mutate('directors.create', ['F']),
  DIRECTOR_UPDATE: mutate('directors.update', ['F']),
  DIRECTOR_MERGE: mutate('directors.merge', ['F', 'V']),
  DIRECTOR_DELETE_PREVIEW: mutate('directors.deletePreview', ['F', 'V'], 'preview'),
  DIRECTOR_DELETE: mutate('directors.delete', ['F', 'V']),
  SERIES_LIST: query('series.list'),
  SERIES_PAGE: query('series.page'),
  SERIES_GET: query('series.get', ['F']),
  SERIES_OPTIONS: query('series.options'),
  SERIES_CREATE: mutate('series.create', ['F']),
  SERIES_UPDATE: mutate('series.update', ['F']),
  SERIES_MERGE: mutate('series.merge', ['F', 'V']),
  SERIES_DELETE_PREVIEW: mutate('series.deletePreview', ['F', 'V'], 'preview'),
  SERIES_DELETE: mutate('series.delete', ['F', 'V']),
  CLASSIFICATION_IMAGE_PAGE: query('classificationImages.page', ['F']),
  CLASSIFICATION_IMAGE_CANDIDATES: query('classificationImages.candidates', ['F']),
  CLASSIFICATION_IMAGE_SET: mutate('classificationImages.set', ['F']),
  SCRAPE_ONE: workflow('scrape.collectVideo', 'videos.applyScrapeCandidate', ['V'], 'Plugin/network on desktop; apply uses captured V and upload refs'),
  PENDING_VIDEO_SCRAPE_COUNT: query('pendingVideoScrapes.count'),
  PENDING_VIDEO_SCRAPE_EXISTING_IDS: query('pendingVideoScrapes.existingIds'),
  PENDING_VIDEO_SCRAPE_PAGE: query('pendingVideoScrapes.page'),
  PENDING_VIDEO_SCRAPE_GET: query('pendingVideoScrapes.get', ['Q']),
  PENDING_VIDEO_SCRAPE_LIST: query('pendingVideoScrapes.list'),
  PENDING_VIDEO_SCRAPE_CONFIRM: mutate('pendingVideoScrapes.confirm', ['V', 'Q']),
  PENDING_VIDEO_SCRAPE_DISCARD: mutate('pendingVideoScrapes.discard', ['V', 'Q']),
  SCRAPE_BATCH_START: workflow('scrape.batchVideo.start', 'targetLists.create', ['V'], 'Desktop schedules collection; each apply is videos.applyScrapeCandidate'),
  SCRAPE_BATCH_CANCEL: workflow('scrape.batchVideo.cancel', undefined, [], 'Stops desktop collection; does not roll back accepted catalog writes'),
  SCRAPE_BATCH_PROGRESS: event('Desktop batch projection'),
  SCRAPE_VIDEO_BATCH_START: workflow('scrape.batchVideo.start', 'targetLists.create', ['V'], 'Same catalog apply path as SCRAPE_BATCH_START'),
  SCRAPE_VIDEO_BATCH_CANCEL: workflow('scrape.batchVideo.cancel', undefined, [], 'Stops desktop collection only'),
  SCRAPE_VIDEO_BATCH_PROGRESS: event('Desktop batch projection'),
  SCRAPE_VIDEO_BATCH_COUNT: workflow('scrape.batchVideo.count', 'videos.list', [], 'Count uses manage list/target list, not a local sqlite scan in remote mode'),
  SCRAPE_REMATCH_BATCH_START: workflow('scrape.rematch.start', 'targetLists.create', ['V'], 'Desktop rematch collection; apply keeps original V'),
  SCRAPE_REMATCH_BATCH_CANCEL: workflow('scrape.rematch.cancel', undefined, [], 'Stops desktop collection only'),
  SCRAPE_REMATCH_BATCH_PROGRESS: event('Desktop rematch projection'),
  SCRAPE_REMATCH_COUNT: workflow('scrape.rematch.count', 'videos.list', []),
  BATCH_SCRAPE_STATE: workflow('scrape.batch.state', 'tasks.get', []),
  BATCH_SCRAPE_PAUSE: workflow('scrape.batch.pause', undefined, [], 'Pauses desktop collection'),
  BATCH_SCRAPE_RESUME: workflow('scrape.batch.resume', undefined, [], 'Resumes desktop collection with frozen target list'),
  BATCH_SCRAPE_DISCARD: workflow('scrape.batch.discard', undefined, [], 'Drops desktop working state only'),
  AVATAR_AUTO_CROP_BATCH_BEGIN: workflow('actress.crop.batch.begin', undefined, [], 'Desktop working set'),
  AVATAR_AUTO_CROP_BATCH_TARGETS: workflow('actress.crop.batch.targets', 'actresses.listPage', ['A']),
  AVATAR_AUTO_CROP_BATCH_END: workflow('actress.crop.batch.end', undefined, []),
  SCRAPER_LIST: desktop('Plugin list on this computer'),
  SCRAPER_PLUGIN_DETAILS: desktop('Plugin details on this computer'),
  PLUGIN_IMPORT: desktop('Install plugin package on this computer'),
  SCRAPER_PLUGIN_EXPORT: desktop('Export plugin package'),
  SCRAPER_PLUGIN_PACKAGE: desktop('Package plugin'),
  SCRAPER_PLUGIN_UPDATE: desktop('Update plugin on this computer'),
  SCRAPER_PLUGIN_DELETE: desktop('Delete plugin on this computer'),
  SCRAPER_SERVICE_CONFIG_GET: desktop('Scraper service secrets stay on this computer'),
  SCRAPER_SERVICE_CONFIG_SAVE: desktop('Scraper service secrets stay on this computer'),
  SCRAPER_SERVICE_CONFIG_TEST: desktop('Scraper service probe on this computer'),
  SCRAPER_SERVICE_CONFIG_CLEAR: desktop('Scraper service secrets stay on this computer'),
  SCRAPER_COMPOSITE_CREATE: desktop('Composite scraper config on this computer'),
  SCRAPER_COMPOSITE_UPDATE: desktop('Composite scraper config on this computer'),
  SCRAPER_COMPOSITE_DELETE: desktop('Composite scraper config on this computer'),
  ACTRESS_SCRAPER_LIST: desktop('Actress plugin list on this computer'),
  ACTRESS_SCRAPER_PLUGIN_DETAILS: desktop('Actress plugin details'),
  ACTRESS_SCRAPER_PLUGIN_EXPORT: desktop('Export actress plugin'),
  ACTRESS_SCRAPER_PLUGIN_PACKAGE: desktop('Package actress plugin'),
  ACTRESS_SCRAPER_PLUGIN_UPDATE: desktop('Update actress plugin'),
  ACTRESS_SCRAPER_PLUGIN_DELETE: desktop('Delete actress plugin'),
  ACTRESS_SCRAPER_COMPOSITE_CREATE: desktop('Actress composite scraper'),
  ACTRESS_SCRAPER_COMPOSITE_UPDATE: desktop('Actress composite scraper'),
  ACTRESS_SCRAPER_COMPOSITE_DELETE: desktop('Actress composite scraper'),
  ACTRESS_SCRAPE_ONE: workflow('scrape.collectActress', 'actresses.applyScrapeCandidate', ['A'], 'Desktop collect; catalog apply with original A'),
  ACTRESS_SCRAPE_BATCH_COUNT: workflow('scrape.batchActress.count', 'actresses.listPage', []),
  ACTRESS_SCRAPE_BATCH_START: workflow('scrape.batchActress.start', 'targetLists.create', ['A']),
  ACTRESS_SCRAPE_BATCH_CANCEL: workflow('scrape.batchActress.cancel', undefined, []),
  ACTRESS_SCRAPE_BATCH_PROGRESS: event('Desktop actress batch projection'),
  ACTRESS_AVATAR_AUTO_CROP_REQUEST: event('Main asks renderer to crop; not a catalog write'),
  ACTRESS_AVATAR_AUTO_CROP_RESULT: workflow('actress.crop.result', 'actresses.applyCrop', ['A'], 'Renderer returns pixels to main; catalog apply checks source digest/version'),
  PLUGIN_DEV_AGENT_START: desktop('Plugin developer agent'),
  PLUGIN_DEV_AGENT_MESSAGE: desktop('Plugin developer agent'),
  PLUGIN_DEV_AGENT_CANCEL: desktop('Plugin developer agent'),
  PLUGIN_DEV_AGENT_RELEASE_BROWSER: desktop('Plugin developer agent'),
  PLUGIN_DEV_AGENT_SNAPSHOT: desktop('Plugin developer agent'),
  PLUGIN_DEV_AGENT_CLEAR_HISTORY: desktop('Plugin developer agent'),
  PLUGIN_DEV_AGENT_DISCARD_UNRECOVERABLE: desktop('Plugin developer agent'),
  PLUGIN_DEV_AGENT_EVENT: event('Plugin developer agent event'),
  PLUGIN_DEV_AGENT_EXPORT_WORK_LOG: desktop('Plugin developer agent'),
  PLUGIN_DEV_DRY_RUN: desktop('Plugin developer dry run'),
  PLUGIN_DEV_INSTALL: desktop('Install from plugin developer'),
  LIBRARY_CURATOR_START: workflow('curator.start', undefined, [], 'Desktop conversation; tools are fixed manage reads'),
  LIBRARY_CURATOR_MESSAGE: workflow('curator.message', undefined, [], 'Must not open local library.db in remote mode'),
  LIBRARY_CURATOR_CANCEL: workflow('curator.cancel', undefined, []),
  LIBRARY_CURATOR_SNAPSHOT: workflow('curator.snapshot', undefined, []),
  AGENT_METADATA_START: workflow('agentMetadata.start', 'agentMetadata.findReady', ['V', 'A', 'F'], 'Desktop collection; catalog lookup only'),
  AGENT_METADATA_RESUME: workflow('agentMetadata.resume', undefined, []),
  AGENT_METADATA_CANCEL: workflow('agentMetadata.cancel', undefined, []),
  AGENT_METADATA_SNAPSHOT: workflow('agentMetadata.snapshot', undefined, []),
  AGENT_METADATA_FIND_READY: query('agentMetadata.findReady', ['V', 'A', 'F']),
  AGENT_METADATA_PLAN: workflow('agentMetadata.plan', 'agentMetadata.findReady', ['V', 'A', 'F'], 'Plan is desktop review; apply is catalog'),
  AGENT_METADATA_APPLY: mutate('agentMetadata.apply', ['V', 'A', 'F', 'Q']),
  AGENT_METADATA_DISCARD: mutate('agentMetadata.discard', ['Q']),
  AGENT_METADATA_SNAPSHOT_CHANGED: event('Desktop metadata collection event'),
  PLAYLIST_IMPORT_START: workflow('playlistImport.start', undefined, [], 'External site session on desktop'),
  PLAYLIST_IMPORT_SNAPSHOT: workflow('playlistImport.snapshot', undefined, []),
  PLAYLIST_IMPORT_CONTROL: workflow('playlistImport.control', 'playlists.applyImport', ['P', 'L', 'V'], 'Final apply is playlists.applyImport'),
  PLAYLIST_IMPORT_SNAPSHOT_CHANGED: event('Desktop playlist import event'),
  PLAYER_PLAY: workflow('player.playLocal', 'play.grant', ['R', 'G'], 'Local uses guarded file handle; remote uses play.grant'),
  PLAYER_REVEAL: unavailable('Remote mode cannot reveal a desktop path'),
  PLAYER_OPEN_RESOURCE: workflow('player.openResource', 'play.grant', ['R', 'G'], 'External links open on desktop without Javdex credentials'),
  PLAYER_REVEAL_RESOURCE: unavailable('Remote reveal is unsupported; local reveal stays desktop'),
  ASSET_CRYPTO_SET: unavailable('Server v1 stores plaintext images only'),
  ASSET_CRYPTO_PROGRESS: event('Local encryption progress; hidden in remote mode'),
  ASSET_STORAGE_RELOCATE: unavailable('Server asset location is the data volume'),
  ASSET_FETCH_REMOTE_IMAGE: workflow('assets.fetchRemote', 'uploads.create', [], 'Desktop may download to a temp handle then upload; renderer cannot pass host paths'),
  LLM_TRANSLATE_TO_CHINESE: desktop('Translation is a desktop draft; save still uses videos.edit')
} as const satisfies Record<keyof typeof IPC, IpcDisposition>

export type IpcDispositionKey = keyof typeof IPC_DISPOSITION
